<script type="text/javascript" src="<?=base_url()?>assets/admin/breakpoints/breakpoints.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/js/jquery.cookie.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/jquery-ui/jquery-ui-1.10.1.custom.min.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/jquery-nestable/jquery.nestable.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/jquery-slimscroll/jquery.slimscroll.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/uniform/jquery.uniform.min.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/js/jquery.blockui.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/js/validate.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/bootstrap-daterangepicker/js/moment.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/bootstrap-daterangepicker/js/date.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/bootstrap-daterangepicker/js/daterangepicker.js"></script>	
<script type="text/javascript" src="<?=base_url()?>assets/admin/js/jquery.livequery.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/upload-process/plupload.full.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/fancybox/source/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/flow-player/flowplayer-3.2.12.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/editor/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/bootstrap-datepicker/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/jquery.knob.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/jquery-panzoom.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/pointer_events_polyfill.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/avatar/js/main.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/jquery.sticky/jquery.sticky.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/js/admin.js"></script>
<script type="text/javascript" src="<?=base_url()?>assets/admin/js/app.js"></script>
<script type="text/javascript">Avatar.avatar_scale_load('<?=$this->session->userdata('admin_avatar')?>');</script>